[package]
name = "order"
version = "0.1.0"
edition = "2021"
authors = ["Andres Castiglia <acastiglia@gmail.com>"]

[dependencies]
chrono = "~0.4"
log = "~0.4"
serde = { version = "~1.0", features = ["derive"] }
serde_json = "~1.0"
thiserror = "~1.0"
